### ISSUE TITLE
Accessing Targeting Idea Service

### ISSUE THREAD

**Issue by Leszek-Sieminski** [jburkhardt/RAdwords#108]
Hi!
First of all, thanks for all your hard work and this wonderful package! I'm writing because found Targeting Idea Service report in AdWords API ([link](https://developers.google.com/adwords/api/docs/reference/v201809/TargetingIdeaService)). However, it does not appear in available reports in RAdwords. I was wondering if it is in development or you decided to not include it for some reason?
Thanks!

**Comment by jburkhardt** [comment]
Hi @Leszek-Sieminski 
Thank you for using RAdwords and your feedback! Yes, we consider integrating the Targeting Idea Service. Due to limited resources, we did not proceed with the development of other services other than the reporting service of the Google Ads API lately. In the meantime, you could have a look into this project where you will find some R code to access the targeting idea service: https://github.com/adviso/RAdwordsPlus
