### ISSUE TITLE
ADS_PERFORMANCE_REPORT  warning message. Not downloading full data

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RAdwords#11]
I am unable to pull all ads in my account. It pulls some then shows a warning message. Is this a ram or memory issue? How do I overcome this to download all ad data? I am able to download much more observations in keywords report with no problem.

Here is the warning message:
Warning messages:
1: In nchar(str) * 4L : NAs produced by integer overflow
2: In scan(file, what, nmax, sep, dec, quote, skip, nlines, na.strings,  :
  EOF within quoted string

Here is my code:
adbody <- statement(select=c('CampaignName','CampaignStatus', 'AdGroupName','AdGroupStatus','Id','Status','Headline', 'Description1', 'Description2', 'Clicks','Cost','DisplayUrl',"Url"),
                     report="AD_PERFORMANCE_REPORT", start=start, end=end)
 addata <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=adbody)

**Comment by jburkhardt** [comment]
Unfortunately I can't reproduce the warnings. I pulled more than 4.000.000 ads at once without any warnings.

Do you get the warnings if you set `transformation` and `changeNames` to `FALSE`?
This returns the raw data format from the API:
```
addata <- getData(clientCustomerId='xxx-xxx-xxxx',
                              google_auth=google_auth ,
                              statement=adbody,
                              transformation=F,
                              changeNames=F)
```

In the meantime a workaround solution could be to pull smaller amounts of data. For instance you pull the ads for each campaign separately and combine the data subsequently.

**Comment by D-sizzle** [comment]
Thanks. When I try your example (transformation=F and changeNames=F)  I only get one error opposed to 2 but it doesn't convert to a dataframe.

Warning message:
In nchar(str) * 4L : NAs produced by integer overflow

I am able to rbind by CampaignName as a work around like you mentioned. Thank you. It would be optimal to also filter by 'AdType' and 'Status' which I'm not able to with the where arg.

I did check and I have way more ads in my account than the quantity in addata in R. I was looking to pull about 2 million but could only get around 8k. There were no NA's, its just the number of observations did not equal the total amount in my account. Filtering by campaign works for now, so thank you!

From everything im researching the issue may be my ram. I have 2.4Ghz processor, 8GB RAM and 64-bit OS. What specs do you have and recommend?

**Comment by jburkhardt** [comment]
**1 Filtering**
You can use *Status* as a filter. Example:
```
adbody <- statement(select=c('CampaignName','CampaignStatus', 'AdGroupName','AdGroupStatus','AdType','Status','Headline', 'Description1', 'Description2', 'Clicks','Cost','DisplayUrl',"Url"),
                    report="AD_PERFORMANCE_REPORT",
                    where="Status = 'ENABLED'",
                    start="20140320",
                    end="20140321")
```
*Ad Type* can not be used as a filter, since it is restricted by the [Adwords API](https://developers.google.com/adwords/api/docs/reference/v201409/AdGroupAdService.TextAd#Ad.Type): *"...Although this field is returned in the response, it is ignored on input and cannot be selected..."*

Generally the package uses AdWords Ad-Hoc Reports and makes use of its complete functionality. If there are any limitations it is due to API restrictions. Please see the documentation of the [Adwords Query Language](https://developers.google.com/adwords/api/docs/guides/awql#grammar) for more detailed information.

**2 Warnings**
It is really difficult to help you in this case, since I can´t reproduce the problem.

`transformation=F` means the data are pulled in the raw format as it is returned by the API. This means the customized function, which transfoms the data into a dataframe does not cause the warning: *In nchar(str) * 4L : NAs produced by integer overflow*. I guess that there are integers data which exceed the maximum size representable by the integer class. Maybe this could be fixed if *integers* are converted into numeric values by default. I will look into this and hopefully come up with a solution soon.

I still don´t understand why you only can pull 8k out of 2 million ads. Could you specify more precicely which kind of ads are missing in the download?
Display Ads? Banner Ads? Text Ads? Search or Google Display Network Campaigns? Deleted Ads? Third Party Ads?

**Comment by mbannert** [comment]
8 GB is not the world but still plenty of RAM. 2 M rows should not be a problem. Let alone if it's just 8K. 
However you can use `object.size(someStuffYouPulledDown)` to determine an object's size in memory.

**Comment by D-sizzle** [comment]
jburkhardt the ad quantity varies. I was just able to download 530k ads, the warnings still show. There was a mix of display, text and shopping ads in there so it's not a certain type. 

Using the 'where' arg and filtering by status works for what I need it for. Thanks!
