### ISSUE TITLE
Google AdWords API sunset 27th April 2022

### ISSUE THREAD

**Issue by Datacove1** [jburkhardt/RAdwords#124]
Hello,

I've received an email from Google (imagine quite a few people have) advising to update to the Google Ads API by 27th April 2022 (so we have time) as the AdWords API will stop working on this date. Will the package source code be updated to reflect this - or do we need to make any changes ourselves to ensure that calls after this date will not fail?

Many thanks,

Jeremy

**Comment by jburkhardt** [comment]
Hello Jeremy,
Thank you very much for pointing this out. Yes, we are aware that the Adwords API will expire in April 2022. The RAdwords package will no longer work then, as it only connects to the Adwords API. To pull data from your Google Ads account after April 2022, you will need to migrate your code to the Google Ads API. Since the two APIs are completely different, we will not include Google Ads API support in the RAdwords package. We are building a new R package that will interface with the Google Ads API. Please be aware that this project is entirely driven by private efforts and there is no funding for the project. However, I cannot guarantee that there will be a new R package in time. Also, the functionality of the Google Ads API is different and therefore your R code will also need to be updated to the new R package / API. If you have production code running on Google Ads data, you should consider using an official Google client library: https://developers.google.com/google-ads/api/docs/client-libs
Kind regards,
Johannes

**Comment by Datacove1** [comment]
Thank you for the swift reply Johannes - and of course I understand the situation you are in - happy to pull information from the API myself going forward should I need, but would love to hear about the development of the new package as it continues!

**Comment by selesnow** [comment]
@Datacove1 

Hello, i build new package `rgoogleads` for work with Google Ads API v8.

You can see documentation in https://selesnow.github.io/rgoogleads/docs/

**Comment by jburkhardt** [comment]
## 👏 Hey hey 👏 

## We released our new package [**{r4googleads}**](https://github.com/banboo-data/r4googleads)

> **The Google AdWords API will [sunset on April 27, 2022](https://ads-developers.googleblog.com/2021/04/upgrade-to-google-ads-api-from-adwords.html).  
> Upgrade to the Google Ads API with our new R package [{r4googleads}](https://github.com/banboo-data/r4googleads).
> Follow our [RAdwords Migration Guide](https://banboo-data.github.io/r4googleads/articles/radwords-migration-guide.html).**

**{r4googleads}** is the official successor of the **{RAdwords}** package.

**Comment by mbannert** [comment]
@Datacove1 ☝️

**Comment by Datacove1** [comment]
Thank you, this looks perfect! Will get all my client's scripts amended!

**Comment by mbannert** [comment]
Good Luck with the migration, let us know how it went.
