### ISSUE TITLE
Querying Criterion.Type

### ISSUE THREAD

**Issue by chipoglesby** [jburkhardt/RAdwords#18]
When I'm pulling metrics for the AUDIENCE_PERFORMANCE_REPORT, I can pull the Audience or the CriterionID.

For example, the audience may be uservertical::80182, which is /Autos & Vehicles/Motor Vehicles/Motor Vehicles by Type/Off-Road Vehicles/Off-Road Vehicles (New), here: http://goo.gl/HJiK99.

Is it possible in in your package to also query the CriterionUserInterest to return the name of the Audience?

I've also noticed similar results when pulling geographic reports, it might possible be done in the same manner.

**Comment by jburkhardt** [comment]
The package can only download data which are available within the adwords api report types. For the audience report see the metrics here:
https://developers.google.com/adwords/api/docs/appendix/reports#audience

If you want to the target group attribute as a name instead of the id, I suggest you download the csv from https://developers.google.com/adwords/api/docs/appendix/in-market-categories
and merge it with your dataframe.

**Comment by chipoglesby** [comment]
Thank you for the clarification, @jburkhardt.
