### ISSUE TITLE
Best Method to Pull Ad Group Level Bid Adjustments 

### ISSUE THREAD

**Issue by D-sizzle** [jburkhardt/RAdwords#28]
Was wondering the best way to do this? Because the ADGROUP_PERFORMANCE_REPORT does not have the option, the CRITERIA_PERFORMANCE_REPORT seems the most relevant. However when pulling data this column just shows "--". But there actually is a modifier in place. Is there another report I should be using for this or is this maybe a bug? -- it was hard to find.

    body <- statement(select=c('BidModifier','CampaignName','AdGroupName','Clicks', 'Impressions', "AveragePosition", 'Cost','ConvertedClicks'),
                        report="CRITERIA_PERFORMANCE_REPORT",
                        start=start1, end=end1)
     data <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=body)

**Comment by jburkhardt** [comment]
Hi, I just recognized your question. Do you mean bid modifications for device type, etc.? I guess this adjustments you only can set on campaign level?

**Comment by D-sizzle** [comment]
Yes, I do mean bid modifications by device type. You can set these at the campaign level OR ad group level. In my case, I have set them at the ad group level and would like to pull it from the API. Is that possible?

https://support.google.com/adwords/answer/2732132?hl=en

**Comment by jburkhardt** [comment]
I cannot see why the API does not return any data. I suppose this has something to do with Adwords API per se.
I forwarded the question to Adwords API forum:
https://groups.google.com/forum/#!topic/adwords-api/SopAeS25_jU
Let´s see if anyone can help out.

**Comment by jburkhardt** [comment]
I have an update from the Adwords API developer team:

The CRITERIA_PERFORMANCE_REPORT will only show you bid modifiers set via the [BiddableAdGroupCriterion.bidModifier](https://developers.google.com/adwords/api/docs/reference/v201509/AdGroupCriterionService.BiddableAdGroupCriterion#bidmodifier) field. Bid modifiers set via [AdGroupBidModifierService](https://developers.google.com/adwords/api/docs/reference/v201509/AdGroupBidModifierService) are not retrievable through reports.

Unfortunately this means you cannot download bid modifier information with RAdwords if you set the bid modifier in the Adwords interface manually.

To set the bid modifier, you can submit an AdGroupCriterionService.mutate operation and set the [BiddableAdGroupCriterion.bidModifier](https://developers.google.com/adwords/api/docs/reference/v201509/AdGroupCriterionService.BiddableAdGroupCriterion#bidmodifier) field. This will be similar to the [UpdateKeyword example](https://github.com/googleads/googleads-dotnet-lib/blob/master/examples/AdWords/CSharp/v201509/BasicOperations/UpdateKeyword.cs), only you'll set bidModifier instead of the biddingStrategyConfiguration.

As this circumstances are not related to any issues with RAdwords directly, I will close the issue.

**Comment by D-sizzle** [comment]
Thanks for trying. In case anyone else is looking to do this -- I found an adwords script that shows how to automate the pull.

https://tools.optmyzr.com/scriptdownload/getscript/18
