### ISSUE TITLE
HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by amrrs** [jburkhardt/RAdwords#45]
After successfully authenticating, Could not download any data. Can you please help?

![image](https://cloud.githubusercontent.com/assets/5347322/14561117/ec53b318-0331-11e6-82dc-aff0bb5ec8ba.png)

Output:

```
* upload completely sent off: 116 out of 116 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: text/xml
< Date: Fri, 15 Apr 2016 12:13:42 GMT
< Expires: Fri, 15 Apr 2016 12:13:42 GMT
< Cache-Control: private, max-age=0
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-XSS-Protection: 1; mode=block
< Server: GSE
< Accept-Ranges: none
< Vary: Accept-Encoding
< Transfer-Encoding: chunked
< 
* Connection #0 to host adwords.google.com left intact
Error in `[.default`(xj, i) : 
  only 0's may be mixed with negative subscripts
```

**Comment by jburkhardt** [comment]
Do you use an Adwords API Test Account?  
Please execute ```getData(..., transformation=F) ``` with transformation set to FALSE. What is the prompt output?

**Comment by amrrs** [comment]
I'm using an approved API Account. The Google App was created from a different account. But the authentication was done from the actual Manager account that holds the API. 

Still error after setting transformation = F.

![image](https://cloud.githubusercontent.com/assets/5347322/14563423/8f54ecfa-033f-11e6-912f-12bc38a0d90e.png)

**Comment by jburkhardt** [comment]
Of course the error still exist. Transformation = false just prints the raw message you receive from the API.

It says wrong: Invalid Token Header. This means your authentication is not correct!
I guess you mixed something up with the different accounts. It´s difficult to help you with that, since this is an issue on your behalf and not an issue with the package per se.

**Comment by jburkhardt** [comment]
Please make sure that you qualify for the following:

In order to access the AdWords API you need to satisfy the following:  

- Google API project
- AdWords MCC (my client center)
- AdWords API Developer Token


Missing one of the above mentioned items you cannot access the AdWords API.

### Google API Project

Set up a [Google API project](https://console.developers.google.com) for **native apps**. The Google API project provides a **Client Id** and **Client Secret** which is necessary for the authentication.

### Adwords MCC

Moreover you need to have a Adwords MCC. A single AdWords account is not sufficient.

### AdWords Developer Token

Once your AdWords MCC is set up you have to apply for an AdWords developer token. 

**Important:**  An AdWords API Test Account will not allow you to load data.

**Comment by amrrs** [comment]
Is it mandatory to have the project created from the same id that owns the MCC account?

**Comment by jburkhardt** [comment]
I guess so. Why don´t you use your MCC master account (email) and create an API project with that same account?

**Comment by prasoonsrivas** [comment]
Hi  

can u please elaborate these steps 

In order to access the AdWords API you need to satisfy the following:

1 Google API project
2 AdWords MCC (my client center)
3 AdWords API Developer Token

**Comment by jburkhardt** [comment]
A detailed documentation is in progress. Meanwhile you can have a look here:
https://github.com/rstats-lab/radwords-docs/blob/master/docs/requirements.md
Hope that answers all your questions.

**Comment by prasoonsrivas** [comment]
Thanks a lot
can i know when the detailed documentation will be available and I
Did't understand the line "A single AdWords account is not sufficient."
<Adwords MCC Moreover you need to set up an AdWords My Client Center. A single AdWords account is not sufficient.>

**Comment by jburkhardt** [comment]
You can read the main content already here:
https://github.com/rstats-lab/radwords-docs/tree/master/docs
If you follow and star the RAdwords repository you will be notified about all updates.

"A single AdWords account is not sufficient." This just means that your Adwords account has to be linked a Adwords MCC. If you only have one Adwords account that´s just fine. I hope there is no inconvenience anymore.
