### ISSUE TITLE
Does it have support for video campaign performance?

### ISSUE THREAD

**Issue by NabeelahB** [jburkhardt/RAdwords#46]
Hi,
I wanted to know if we can extract video campaign reports using this package. If yes, then how to do the same.

Regards,
Tabu

**Comment by jburkhardt** [comment]
Yes! Since RAdwords 0.1.9 you can query data related with the following report:
https://developers.google.com/adwords/api/docs/appendix/reports/video-performance-report
Please make sure you install the latest RAdwords version from github (instead of CRAN).
Just use the Video Performance Report as report type in ```getData()```.
Hope that helps!
