### ISSUE TITLE
KEYWORDS_PERFORMANCE_REPORT, CPC Bid showing as "NA"

### ISSUE THREAD

**Issue by connelldan** [jburkhardt/RAdwords#8]
Not sure why, but all my Max. CPC bids are not pulling down for a keyword report. Is this a known issue or am I pulling it wrong?

 perfbody <- statement(select=c('AccountDescriptiveName','Date', 'Device', 'CampaignName', 'KeywordText', 'CpcBid', 'AdGroupName','KeywordMatchType', 'Clicks', 'Cost', 'Conversions', 'ConversionValue'),
report="KEYWORDS_PERFORMANCE_REPORT", start=start, end=end)
 perfdata <- getData(clientCustomerId='xxx-xxx-xxxx', google_auth=google_auth ,statement=perfbody)

**Comment by D-sizzle** [comment]
This fix did work for a brief amount of time. I am however again seeing all NA for Max.CPC.

**Comment by jburkhardt** [comment]
Hi,

I can't reproduce your problem. For all keywords which I **set bids manually** the package/API returns correct data.
Do you use the Google bidding tools like Conversion- or Click-Optimizer? In this case there are no Max.CPC data since you never set it in Adwords per se. Could you please review the campaign settings and bidding options? I guess this could explain the NA data in Max.CPC.

I'm looking forward to your feedback!
Kind regards,
Johannes

**Comment by D-sizzle** [comment]
Ah yes, yes. The NA's were showing for display campaigns that had a different bidding strategy. Thanks!
